services:
  repl:
    depends_on:
      - consul
    logging:
      driver: json-file
      options:
        max-size: "10m"
    image: shinhwagk/mysql-sync:0.2.10
    command: -repl - 9091:9091
    volumes:
      - ./config.yml:/etc/mysqlsync/config.yml
    restart: on-failure
  dest:
    logging:
      driver: json-file
      options:
        max-size: "10m"
    image: shinhwagk/mysql-sync:0.2.14
    command: -dest -name sc_db3_3317
    ports:
      - 9092:9092
    volumes:
      - ./config.yml:/etc/mysqlsync/config.yml
    restart: on-failure
  consul:
    image: hashicorp/consul:1.19.1
  prometheus:
    image: prom/prometheus:v2.52.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prom-alert.yml:/etc/prometheus/prom-alert.yml
  temeral:
    image: rockylinux:9
    command: sleep inf
  grafana:
    image: grafana/grafana:10.4.4
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
  alertmanager-webhook:
    image: denoland/deno:1.44.4
    volumes:
      - ./alertmanager-webhook:/app/
    command: deno run --allow-all /app/main.ts
  alertmanager:
    image: prom/alertmanager:v0.27.0
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
