global:
  scrape_interval: 10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - "prom-alert.yml"

scrape_configs:
  - job_name: "mysqlsync"
    static_configs:
      - targets: ["172.16.0.179:9091"]
      - targets: ["dest:9092"]

