[tool.ruff]
ignore = [
    "E501", # Line too long, handled by black
    "F403", # from module import *' used, It should be removed afterwad
    "F405", # same to F403
]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
