{
 "title": "MysqlSync",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "mysqlsync_destination_delay", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Extract & Applier",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "delta(mysqlsync_destination_applier_operations[1m])",
     "legendFormat": "applier"
    },
    {
     "expr": "delta(mysqlsync_replication_extract_operations[1m])",
     "legendFormat": "extract"
    }
   ]
  },
  {
   "title": "Transaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "delta(mysqlsync_destination_trx[1m])",
     "legendFormat": "trx"
    },
    {
     "expr": "delta(mysqlsync_destination_merge_trx[1m])",
     "legendFormat": "merge-trx"
    }
   ]
  },
  {
   "title": "Tcp send & receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "delta(mysqlsync_replication_tcp_server_send_operations[1m])",
     "legendFormat": "repl-send"
    },
    {
     "expr": "delta(mysqlsync_destination_tcp_client_receive_operations[1m])",
     "legendFormat": "dest-receive"
    }
   ]
  },
  {
   "title": "DML",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "delta(mysqlsync_destination_dml_delete_times[1m])",
     "legendFormat": "delete"
    },
    {
     "expr": "delta(mysqlsync_destination_dml_insert_times[1m])",
     "legendFormat": "insert"
    }
   ]
  }
 ]
}