services:
  repl:
    depends_on:
      - hjdb
    image: shinhwagk/mysql-sync:0.0.2
    command: -repl
      - 9091:9091
    volumes:
      - ./config.yml:/etc/mysql-sync/config.yml
  dest:
    depends_on:
      - repl
    image: shinhwagk/mysql-sync:0.0.2
    command: -dest
    ports:
      - 9092:9091
    volumes:
      - ./config.yml:/etc/mysql-sync/config.yml
  hjdb:
    image: shinhwagk/hjdb:0.0.6
    volumes:
      - ./hjdb:/var/lib/hjdb