FROM --platform=linux/amd64 ubuntu:24.04

RUN apt update
RUN apt install -y zsh git wget lsb-release gnupg

# RUN sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"