replication:
  name: "xxxx"
  tcpaddr: "0.0.0.0:9998"
  serverid: 9999
  host: "db1"
  port: 3306
  user: "root"
  password: "root_password"
  loglevel: 1
  settings:
    cache: 1000
destination:
  tcpaddr: "127.0.0.1:9998"
  settings:
    cache: 1000
  destinations:
    db2:
      mysql:
        dsn: "root:root_password@tcp(db2:3306)/?autocommit=false&time_zone='%2B00:00'"
        skip_errors: 1007,1008,1050,1051,1054,1060,1061,1068,1091,1146
      sync:
        replicate:
          do_db: test
          ignore_tab: test.year_table
        gtidsets: ""
        cache_size: 100000
      prom:
        export: 9092
      loglevel: 1
    db3:
      mysql:
        dsn: "root:root_password@tcp(db3:3306)/?autocommit=false&time_zone='%2B00:00'"
        skip_errors: 1007,1008,1050,1051,1054,1060,1061,1068,1091,1146
      sync:
        gtidsets: ""
      loglevel: 1
      prom:
        export: 9093
hjdb:
  addr: hjdb:8000
prometheus:
  name: xx
