name: Build GO

on:
  push:
    branches:
      - main
    paths:
      - 'version'
  pull_request:
    branches:
      - main
    paths:
      - 'version'

jobs:
  build_and_release:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.go
          push: true
          tags: shinhwagk/mysql-sync:${{ steps.version.outputs.version }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Done
        run: echo "The image has been successfully built and pushed."

      - id: version
        run: echo "::set-output name=version::$(cat version)"