name: Build Release

on:
  push:
    paths:
      - "version"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Get version
        run: echo "VERSION=$(cat version)" >> $GITHUB_ENV

      - name: Build the Go application
        run: |
          VERSION=${{ env.VERSION }}
          go mod tidy
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags="-s -w" -o mysqlsync-amd64-${VERSION} ./src/*.go
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -a -ldflags="-s -w" -o mysqlsync-arm64-${VERSION} ./src/*.go
          ls -lrt

      # - name: Upload binaries to release
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     file: mysqlsync-amd64-${{ env.VERSION }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release and Upload binaries
        uses: softprops/action-gh-release@v2
        with:
          files: |
            mysqlsync-amd64-${{ github.ref_name }}
            mysqlsync-arm64-${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
