name: MySQL Service Example

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql8036_1:
        image: shinhwagk/mysql:8.0.36
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_MYSQLD_ARGS: "--server-id=1000 --log-bin=mysql-bin --gtid-mode=on --enforce-gtid-consistency=on"
        ports:
          - 33061:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      mysql8036_2:
        image: shinhwagk/mysql:8.0.36
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_MYSQLD_ARGS: "--server-id=1000 --log-bin=mysql-bin --gtid-mode=on --enforce-gtid-consistency=on"
        ports:
          - 33062:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    #   percona803628:
    #     image: percona:8.0.36-28
    #     env:
    #       MYSQL_ROOT_PASSWORD: root_password
    #       MYSQL_DATABASE: test_db
    #     ports:
    #       - 33062:3306
    #     options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    #   percona803527:
    #     image: percona:8.0.35-27
    #     env:
    #       MYSQL_ROOT_PASSWORD: root_password
    #       MYSQL_DATABASE: test_db
    #     ports:
    #       - 33063:3306
    #     options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - run: mysql -h127.0.0.1 -P33061 -uroot -proot_password -e 'SELECT version()'

      - run: |
          set -e

          mysql -h127.0.0.1 -P33061 -uroot -proot_password <test_data.sql
          function cmd1(){
            mysqlbinlog -h127.0.0.1 -P33061 -uroot -proot_password --read-from-remote-server --to-last-log -v mysql-bin.000001
          }
          function cmd2(){
            cargo run 2>binlog_stats.log
          }
          function cmd3(){
            mysql -h127.0.0.1 -P33062 -uroot -proot_password -v >cmd3.out.log 2>cmd3.err.log
          }
          
          cmd1 | cmd2 | cmd3

          cat cmd3.err.log
          cat cmd3.out.log | wc -l

          cat binlog_stats.log

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Testing data validation after using mysqlbinlog-statistics.
        run: |
          pip install mysql-compare
          curl -OLs https://raw.githubusercontent.com/shinhwagk/mysql-compare-tables/main/scripts/dbcompare.py

          mkdir mysql-compare
          cd mysql-compare
          python ../dbcompare.py
          ls -l ./
          find ./ -type f -name '*.err.log' | while read file; do
            cat $file
          done
          find ./ -type f -name '*.diff.log' | while read file; do
            cat $file
          done

          # echo "check diff rows of tables"
          # find ./ -type f -name '*.diff.*'

          # ls -l ./
        env:
          ARGS_SOURCE_DSN: root/root_password@127.0.0.1:33061
          ARGS_TARGET_DSN: root/root_password@127.0.0.1:33062
          ARGS_DATABASES: test
      - name: Testing Gtid after using mysqlbinlog-statistics.
        run:
          mysql -h127.0.0.1 -P33061 -uroot -proot_password -e "select @@server_uuid; show master status\G"
          mysql -h127.0.0.1 -P33062 -uroot -proot_password -e "select @@server_uuid; show master status\G"

      # - run: |
      #     time mysqlbinlog -h127.0.0.1 -P33061 -uroot -proot_password --read-from-remote-server --to-last-log -v mysql-bin.000001 | bash ./binlogentry_statistics.sh >/dev/null

      #     mysqlbinlog -h127.0.0.1 -P33061 -uroot -proot_password --read-from-remote-server --to-last-log -v mysql-bin.000001 | bash ./binlogentry_statistics.sh | grep -i 'create table '

      #     [[ $? == 0 ]] && exit 0
      #     mysqlbinlog -h127.0.0.1 -P33061 -uroot -proot_password --read-from-remote-server --to-last-log -v mysql-bin.000001 | bash -x ./binlogentry_statistics.sh

