name: MySQL Service Example

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql8036:
        image: shinhwagk/mysql:8.0.36
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_MYSQLD_ARGS: "--server-id=1000 --log-bin=mysql-bin --gtid-mode=on --enforce-gtid-consistency=on"
        ports:
          - 33061:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    #   percona803628:
    #     image: percona:8.0.36-28
    #     env:
    #       MYSQL_ROOT_PASSWORD: root_password
    #       MYSQL_DATABASE: test_db
    #     ports:
    #       - 33062:3306
    #     options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    #   percona803527:
    #     image: percona:8.0.35-27
    #     env:
    #       MYSQL_ROOT_PASSWORD: root_password
    #       MYSQL_DATABASE: test_db
    #     ports:
    #       - 33063:3306
    #     options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check mysql client version
        run: mysql --version
        
      - run: mysql -h127.0.0.1 -P33061 -uroot -proot_password -e 'SELECT version()'

      - run: mysql -h127.0.0.1 -P33061 -uroot -proot_password <test_data.sql

      - run: |
        mysqlbinlog -h127.0.0.1 -P33061 -uroot -proot_password --read-from-remote-server --to-last-log -v mysql-bin.000001 | bash ./binlogentry_statistics.sh
        [[ $? == 0 ]] && exit 0
        mysqlbinlog -h127.0.0.1 -P33061 -uroot -proot_password --read-from-remote-server --to-last-log -v mysql-bin.000001 | bash -x ./binlogentry_statistics.sh
